### ISSUE TITLE
Follow type naming convention

### ISSUE THREAD

**Issue by Aakashx2838** [nischhal-hub/BlogIn#2]
Nothing too important but code becomes clean if you correctly name types and interfaces

Here's how I approach it:

1. Types

If the type is of a component prop then I simply name it as TProps and never export it
![image](https://github.com/nischhal-hub/BlogIn/assets/101621390/322e1e54-d9f8-4280-9d43-ce6ec175489b)

If the type is of api response and such I name type such as T[[Database entity name]]
![image](https://github.com/nischhal-hub/BlogIn/assets/101621390/cea7e84a-134d-429b-bb15-a90221e0a9e4)

If the type comes is of an api response and dependent of another existing type in your system it is always good to derive it (use ts utility functions)
![image](https://github.com/nischhal-hub/BlogIn/assets/101621390/a308a879-f548-4274-961a-597900c9e847)

Use enums wherever you can (consistent comparison and all)
![image](https://github.com/nischhal-hub/BlogIn/assets/101621390/ef11b3c8-2d82-4499-ad57-4889f9852c9b)

2. Interfaces (I follow same rules for interfaces like I do for types I just prefix everything with an I instead of a T)

Eg. TAuthor => IAuthor

**Comment by Aakashx2838** [comment]
Also if the API you're using gives a consistent response, create generics. Here's an example

![image](https://github.com/nischhal-hub/BlogIn/assets/101621390/fafe1fe6-dd9e-4bcf-b62f-39b876223cd1)

**Comment by nischhal-hub** [comment]
Completed.
